# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gregwar/Rhoban/Utils

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gregwar/Rhoban/Utils

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gregwar/Rhoban/Utils/CMakeFiles /home/gregwar/Rhoban/Utils/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gregwar/Rhoban/Utils/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RhobanUtils

# Build rule for target.
RhobanUtils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RhobanUtils
.PHONY : RhobanUtils

# fast build rule for target.
RhobanUtils/fast:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/build
.PHONY : RhobanUtils/fast

#=============================================================================
# Target rules for targets named TinyXml

# Build rule for target.
TinyXml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TinyXml
.PHONY : TinyXml

# fast build rule for target.
TinyXml/fast:
	$(MAKE) -f xml/TinyXml/CMakeFiles/TinyXml.dir/build.make xml/TinyXml/CMakeFiles/TinyXml.dir/build
.PHONY : TinyXml/fast

anyoption.o: anyoption.cpp.o
.PHONY : anyoption.o

# target to build an object file
anyoption.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/anyoption.cpp.o
.PHONY : anyoption.cpp.o

anyoption.i: anyoption.cpp.i
.PHONY : anyoption.i

# target to preprocess a source file
anyoption.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/anyoption.cpp.i
.PHONY : anyoption.cpp.i

anyoption.s: anyoption.cpp.s
.PHONY : anyoption.s

# target to generate assembly for a file
anyoption.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/anyoption.cpp.s
.PHONY : anyoption.cpp.s

chrono.o: chrono.cpp.o
.PHONY : chrono.o

# target to build an object file
chrono.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/chrono.cpp.o
.PHONY : chrono.cpp.o

chrono.i: chrono.cpp.i
.PHONY : chrono.i

# target to preprocess a source file
chrono.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/chrono.cpp.i
.PHONY : chrono.cpp.i

chrono.s: chrono.cpp.s
.PHONY : chrono.s

# target to generate assembly for a file
chrono.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/chrono.cpp.s
.PHONY : chrono.cpp.s

config_file.o: config_file.cpp.o
.PHONY : config_file.o

# target to build an object file
config_file.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/config_file.cpp.o
.PHONY : config_file.cpp.o

config_file.i: config_file.cpp.i
.PHONY : config_file.i

# target to preprocess a source file
config_file.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/config_file.cpp.i
.PHONY : config_file.cpp.i

config_file.s: config_file.cpp.s
.PHONY : config_file.s

# target to generate assembly for a file
config_file.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/config_file.cpp.s
.PHONY : config_file.cpp.s

fifo.o: fifo.cpp.o
.PHONY : fifo.o

# target to build an object file
fifo.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/fifo.cpp.o
.PHONY : fifo.cpp.o

fifo.i: fifo.cpp.i
.PHONY : fifo.i

# target to preprocess a source file
fifo.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/fifo.cpp.i
.PHONY : fifo.cpp.i

fifo.s: fifo.cpp.s
.PHONY : fifo.s

# target to generate assembly for a file
fifo.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/fifo.cpp.s
.PHONY : fifo.cpp.s

file_mngt.o: file_mngt.cpp.o
.PHONY : file_mngt.o

# target to build an object file
file_mngt.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/file_mngt.cpp.o
.PHONY : file_mngt.cpp.o

file_mngt.i: file_mngt.cpp.i
.PHONY : file_mngt.i

# target to preprocess a source file
file_mngt.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/file_mngt.cpp.i
.PHONY : file_mngt.cpp.i

file_mngt.s: file_mngt.cpp.s
.PHONY : file_mngt.s

# target to generate assembly for a file
file_mngt.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/file_mngt.cpp.s
.PHONY : file_mngt.cpp.s

state_machine.o: state_machine.cpp.o
.PHONY : state_machine.o

# target to build an object file
state_machine.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/state_machine.cpp.o
.PHONY : state_machine.cpp.o

state_machine.i: state_machine.cpp.i
.PHONY : state_machine.i

# target to preprocess a source file
state_machine.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/state_machine.cpp.i
.PHONY : state_machine.cpp.i

state_machine.s: state_machine.cpp.s
.PHONY : state_machine.s

# target to generate assembly for a file
state_machine.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/state_machine.cpp.s
.PHONY : state_machine.cpp.s

tests/TestCase.o: tests/TestCase.cpp.o
.PHONY : tests/TestCase.o

# target to build an object file
tests/TestCase.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/tests/TestCase.cpp.o
.PHONY : tests/TestCase.cpp.o

tests/TestCase.i: tests/TestCase.cpp.i
.PHONY : tests/TestCase.i

# target to preprocess a source file
tests/TestCase.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/tests/TestCase.cpp.i
.PHONY : tests/TestCase.cpp.i

tests/TestCase.s: tests/TestCase.cpp.s
.PHONY : tests/TestCase.s

# target to generate assembly for a file
tests/TestCase.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/tests/TestCase.cpp.s
.PHONY : tests/TestCase.cpp.s

threading/Condition.o: threading/Condition.cpp.o
.PHONY : threading/Condition.o

# target to build an object file
threading/Condition.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/Condition.cpp.o
.PHONY : threading/Condition.cpp.o

threading/Condition.i: threading/Condition.cpp.i
.PHONY : threading/Condition.i

# target to preprocess a source file
threading/Condition.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/Condition.cpp.i
.PHONY : threading/Condition.cpp.i

threading/Condition.s: threading/Condition.cpp.s
.PHONY : threading/Condition.s

# target to generate assembly for a file
threading/Condition.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/Condition.cpp.s
.PHONY : threading/Condition.cpp.s

threading/Mutex.o: threading/Mutex.cpp.o
.PHONY : threading/Mutex.o

# target to build an object file
threading/Mutex.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/Mutex.cpp.o
.PHONY : threading/Mutex.cpp.o

threading/Mutex.i: threading/Mutex.cpp.i
.PHONY : threading/Mutex.i

# target to preprocess a source file
threading/Mutex.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/Mutex.cpp.i
.PHONY : threading/Mutex.cpp.i

threading/Mutex.s: threading/Mutex.cpp.s
.PHONY : threading/Mutex.s

# target to generate assembly for a file
threading/Mutex.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/Mutex.cpp.s
.PHONY : threading/Mutex.cpp.s

threading/Thread.o: threading/Thread.cpp.o
.PHONY : threading/Thread.o

# target to build an object file
threading/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/Thread.cpp.o
.PHONY : threading/Thread.cpp.o

threading/Thread.i: threading/Thread.cpp.i
.PHONY : threading/Thread.i

# target to preprocess a source file
threading/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/Thread.cpp.i
.PHONY : threading/Thread.cpp.i

threading/Thread.s: threading/Thread.cpp.s
.PHONY : threading/Thread.s

# target to generate assembly for a file
threading/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/Thread.cpp.s
.PHONY : threading/Thread.cpp.s

threading/TimedThread.o: threading/TimedThread.cpp.o
.PHONY : threading/TimedThread.o

# target to build an object file
threading/TimedThread.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/TimedThread.cpp.o
.PHONY : threading/TimedThread.cpp.o

threading/TimedThread.i: threading/TimedThread.cpp.i
.PHONY : threading/TimedThread.i

# target to preprocess a source file
threading/TimedThread.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/TimedThread.cpp.i
.PHONY : threading/TimedThread.cpp.i

threading/TimedThread.s: threading/TimedThread.cpp.s
.PHONY : threading/TimedThread.s

# target to generate assembly for a file
threading/TimedThread.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/threading/TimedThread.cpp.s
.PHONY : threading/TimedThread.cpp.s

ticks.o: ticks.cpp.o
.PHONY : ticks.o

# target to build an object file
ticks.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/ticks.cpp.o
.PHONY : ticks.cpp.o

ticks.i: ticks.cpp.i
.PHONY : ticks.i

# target to preprocess a source file
ticks.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/ticks.cpp.i
.PHONY : ticks.cpp.i

ticks.s: ticks.cpp.s
.PHONY : ticks.s

# target to generate assembly for a file
ticks.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/ticks.cpp.s
.PHONY : ticks.cpp.s

timing/Playable.o: timing/Playable.cpp.o
.PHONY : timing/Playable.o

# target to build an object file
timing/Playable.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/Playable.cpp.o
.PHONY : timing/Playable.cpp.o

timing/Playable.i: timing/Playable.cpp.i
.PHONY : timing/Playable.i

# target to preprocess a source file
timing/Playable.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/Playable.cpp.i
.PHONY : timing/Playable.cpp.i

timing/Playable.s: timing/Playable.cpp.s
.PHONY : timing/Playable.s

# target to generate assembly for a file
timing/Playable.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/Playable.cpp.s
.PHONY : timing/Playable.cpp.s

timing/Player.o: timing/Player.cpp.o
.PHONY : timing/Player.o

# target to build an object file
timing/Player.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/Player.cpp.o
.PHONY : timing/Player.cpp.o

timing/Player.i: timing/Player.cpp.i
.PHONY : timing/Player.i

# target to preprocess a source file
timing/Player.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/Player.cpp.i
.PHONY : timing/Player.cpp.i

timing/Player.s: timing/Player.cpp.s
.PHONY : timing/Player.s

# target to generate assembly for a file
timing/Player.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/Player.cpp.s
.PHONY : timing/Player.cpp.s

timing/TickMachine.o: timing/TickMachine.cpp.o
.PHONY : timing/TickMachine.o

# target to build an object file
timing/TickMachine.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/TickMachine.cpp.o
.PHONY : timing/TickMachine.cpp.o

timing/TickMachine.i: timing/TickMachine.cpp.i
.PHONY : timing/TickMachine.i

# target to preprocess a source file
timing/TickMachine.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/TickMachine.cpp.i
.PHONY : timing/TickMachine.cpp.i

timing/TickMachine.s: timing/TickMachine.cpp.s
.PHONY : timing/TickMachine.s

# target to generate assembly for a file
timing/TickMachine.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/TickMachine.cpp.s
.PHONY : timing/TickMachine.cpp.s

timing/TickTimer.o: timing/TickTimer.cpp.o
.PHONY : timing/TickTimer.o

# target to build an object file
timing/TickTimer.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/TickTimer.cpp.o
.PHONY : timing/TickTimer.cpp.o

timing/TickTimer.i: timing/TickTimer.cpp.i
.PHONY : timing/TickTimer.i

# target to preprocess a source file
timing/TickTimer.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/TickTimer.cpp.i
.PHONY : timing/TickTimer.cpp.i

timing/TickTimer.s: timing/TickTimer.cpp.s
.PHONY : timing/TickTimer.s

# target to generate assembly for a file
timing/TickTimer.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/timing/TickTimer.cpp.s
.PHONY : timing/TickTimer.cpp.s

util.o: util.cpp.o
.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i
.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s
.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/util.cpp.s
.PHONY : util.cpp.s

xml/XMLTools.o: xml/XMLTools.cpp.o
.PHONY : xml/XMLTools.o

# target to build an object file
xml/XMLTools.cpp.o:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/xml/XMLTools.cpp.o
.PHONY : xml/XMLTools.cpp.o

xml/XMLTools.i: xml/XMLTools.cpp.i
.PHONY : xml/XMLTools.i

# target to preprocess a source file
xml/XMLTools.cpp.i:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/xml/XMLTools.cpp.i
.PHONY : xml/XMLTools.cpp.i

xml/XMLTools.s: xml/XMLTools.cpp.s
.PHONY : xml/XMLTools.s

# target to generate assembly for a file
xml/XMLTools.cpp.s:
	$(MAKE) -f CMakeFiles/RhobanUtils.dir/build.make CMakeFiles/RhobanUtils.dir/xml/XMLTools.cpp.s
.PHONY : xml/XMLTools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... RhobanUtils"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TinyXml"
	@echo "... anyoption.o"
	@echo "... anyoption.i"
	@echo "... anyoption.s"
	@echo "... chrono.o"
	@echo "... chrono.i"
	@echo "... chrono.s"
	@echo "... config_file.o"
	@echo "... config_file.i"
	@echo "... config_file.s"
	@echo "... fifo.o"
	@echo "... fifo.i"
	@echo "... fifo.s"
	@echo "... file_mngt.o"
	@echo "... file_mngt.i"
	@echo "... file_mngt.s"
	@echo "... state_machine.o"
	@echo "... state_machine.i"
	@echo "... state_machine.s"
	@echo "... tests/TestCase.o"
	@echo "... tests/TestCase.i"
	@echo "... tests/TestCase.s"
	@echo "... threading/Condition.o"
	@echo "... threading/Condition.i"
	@echo "... threading/Condition.s"
	@echo "... threading/Mutex.o"
	@echo "... threading/Mutex.i"
	@echo "... threading/Mutex.s"
	@echo "... threading/Thread.o"
	@echo "... threading/Thread.i"
	@echo "... threading/Thread.s"
	@echo "... threading/TimedThread.o"
	@echo "... threading/TimedThread.i"
	@echo "... threading/TimedThread.s"
	@echo "... ticks.o"
	@echo "... ticks.i"
	@echo "... ticks.s"
	@echo "... timing/Playable.o"
	@echo "... timing/Playable.i"
	@echo "... timing/Playable.s"
	@echo "... timing/Player.o"
	@echo "... timing/Player.i"
	@echo "... timing/Player.s"
	@echo "... timing/TickMachine.o"
	@echo "... timing/TickMachine.i"
	@echo "... timing/TickMachine.s"
	@echo "... timing/TickTimer.o"
	@echo "... timing/TickTimer.i"
	@echo "... timing/TickTimer.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... xml/XMLTools.o"
	@echo "... xml/XMLTools.i"
	@echo "... xml/XMLTools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

