UTILS_SRC = file_mngt.cpp \
 fifo.cpp                 \
 state_machine.cpp        \
 command.cpp              \
 ticks.cpp                \
 util.cpp                 \
 chrono.cpp               \
 anyoption.cpp            \
 config_file.cpp

SOURCES := ticks.cpp util.cpp chrono.cpp

UTILS_SUBDIRS = test xml timing threading
